=== BoldingBruggeman/parsac/client/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="transporttype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="http"/>
      <xs:enumeration value="mysql"/>
      <xs:enumeration value="sqlite"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="booltype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="True"/>
      <xs:enumeration value="False"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nonNegativeDouble">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="transport">
    <xs:complexType>
      <xs:attribute name="type"        type="transporttype" use="required" />
      <xs:attribute name="server"      type="xs:string"     use="optional" />
      <xs:attribute name="user"        type="xs:string"     use="optional" />
      <xs:attribute name="password"    type="xs:string"     use="optional" />
      <xs:attribute name="database"    type="xs:string"     use="optional" />
      <xs:attribute name="path"        type="xs:string"     use="optional" />
      <xs:attribute name="defaultfile" type="xs:string"     use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="file"     type="xs:string" use="optional" />
      <xs:attribute name="namelist" type="xs:string" use="optional" />
      <xs:attribute name="variable" type="xs:string" use="optional" />
      <xs:attribute name="minimum"  type="xs:double" use="optional" />
      <xs:attribute name="maximum"  type="xs:double" use="optional" />
      <xs:attribute name="dummy"    type="booltype"  use="optional" />
      <xs:attribute name="logscale" type="booltype"  use="optional" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="executable">
    <xs:complexType>
      <xs:attribute name="path"     type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="variable">
    <xs:complexType>
      <xs:attribute name="source"              type="xs:string" use="required" />
      <xs:attribute name="modelvariable"       type="xs:string" use="required" />
      <xs:attribute name="spinupyears"         type="xs:nonNegativeInteger" use="optional" />
      <xs:attribute name="maxdepth"            type="nonNegativeDouble" use="optional" />
      <xs:attribute name="relativefit"         type="booltype"  use="optional" />
      <xs:attribute name="logscale"            type="booltype"  use="optional" />
      <xs:attribute name="minscalefactor"      type="xs:double" use="optional" />
      <xs:attribute name="maxscalefactor"      type="xs:double" use="optional" />
      <xs:attribute name="constantscalefactor" type="xs:double" use="optional" />
      <xs:attribute name="minimum"             type="xs:double" use="optional" />
      <xs:attribute name="sd"                  type="nonNegativeDouble" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="transports">
    <xs:complexType>
        <xs:sequence>
          <xs:element ref="transport" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="observations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="variable" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="transports"   minOccurs="1" maxOccurs="1"/>
        <xs:element ref="executable"   minOccurs="1" maxOccurs="1"/>
        <xs:element ref="parameters"   minOccurs="1" maxOccurs="1"/>
        <xs:element ref="observations" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== BoldingBruggeman/parsac/parsac/examples/kinneret_wind.xml
<?xml version="1.0" encoding="utf-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../client/config.xsd">
  <transports>
    <transport type="sqlite"/>
  </transports>
  <executable path="../../../gotm-lake/build/Release/gotm.exe"/>
  <setup path="../../../glm2gotm/test"/>
  <parameters>
    <parameter file="airsea.nml" namelist="airsea" variable="wind_factor" minimum="0." maximum="3."/>
    <parameter file="gotmturb.nml" namelist="turb_param" variable="k_min" minimum="1e-7" maximum="1e-5" logscale="True"/>
    <parameter dummy="True"                                               minimum="0." maximum="1"/>
  </parameters>
  <observations>
    <variable source="../../../glm2gotm/test/temp.obs" modelpath="output.nc" modelvariable="temp" spinupyears="2"/>
  </observations>
</config>

=== BoldingBruggeman/parsac/example/kinneret_wind.xml
<?xml version="1.0" encoding="utf-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../client/config.xsd">
  <transports>
    <transport type="sqlite"/>
  </transports>
  <executable path="../../gotm-lake/build/Release/gotm.exe"/>
  <setup path="../../glm2gotm/test"/>
  <parameters>
    <parameter file="airsea.nml" namelist="airsea" variable="wind_factor" minimum="0." maximum="3."/>
    <parameter dummy="True"                                               minimum="0." maximum="1"/>
  </parameters>
  <observations>
    <variable source="../../glm2gotm/test/sst_extracted.dat" modelpath="output.nc" modelvariable="temp" spinupyears="2" maxdepth="310"/>
  </observations>
</config>
